# Generated by Django 5.1.1 on 2024-09-03 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CSVFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('csv_file_1', models.FileField(blank=True, null=True, upload_to='csv_files/')),
                ('csv_file_2', models.FileField(blank=True, null=True, upload_to='csv_files/')),
                ('result_file', models.FileField(blank=True, null=True, upload_to='csv_files/')),
            ],
        ),
    ]
